### ISSUE TITLE
Port multiline REPL from LFortran to cpp-terminal

### ISSUE THREAD

**Issue by certik** [jupyter-xeus/cpp-terminal#100]
Thanks to [Dominic Poerio](https://gitlab.com/dpoe) we now have a working multi-line REPL in LFortran:

https://gitlab.com/lfortran/lfortran/-/blob/44bad104711796fa0b4743460ea832c0ee04682a/src/bin/lfortran.cpp#L226
https://gitlab.com/lfortran/lfortran/-/blob/44bad104711796fa0b4743460ea832c0ee04682a/src/bin/tpl/cpp-terminal/prompt0.h

We should port it to `cpp-terminal` so that other projects can also use it.

**Comment by dpoerio** [comment]
I did a rough merge of the LFortran terminal.h and terminal_base.h in [this branch](https://github.com/dpoerio/cpp-terminal/tree/multi2). There were ~50 conflicts, but the standalone test compiles, and some of the other examples do as well. I haven't looked in to what exactly is going on with the other cases yet.

**Comment by certik** [comment]
@dpoerio awesome, thanks! Go ahead and submit a PR from the branch and we can work on it.

**Comment by MCWertGaming** [comment]
Well done! Tell me if i can help out somewhere.

**Comment by certik** [comment]
Thanks @dpoerio and @MCWertGaming !

There is some polishing to be done and we'll now use `cpp-terminal` in LFortran directly, but the core of the functionality is implemented!
