### ISSUE TITLE
Fix alt heys

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#106]
As we have discussed in #104 we have to fix issues with the alt keys. The current macro tends to cast values greater than 127 into a char type which results into a runtime error because a char can only hold values from 0 to 127.

**Comment by MCWertGaming** [comment]
update on this: the macros are broken and do really nothing actually. first of all ALT keys return a value below zero which gets casted into a unsigned char (which can't be negative). Then we calculate it + 128 and cast it back into an char (which can just hold up to 127). So in the end it somehow still provides the case `Key < 0`.

@certik would it be enough to just check if the key number is below zero? I haven't found another key that is similar to that. Otherwise i could check on the actual value of the alt key (probably a number that's the char + some value) and create a function you can just easily use.

Also CTRL+I returns TAB key in the keys demo. I would fix that as well.

**Comment by certik** [comment]
I don't have an opinion. If there is a runtime error that we need to fix it. As we discussed, we should move from macros to functions. There was some issue that it required a significant rewrite of some switch statements in one of the examples, but I haven't had time to look into that.

**Comment by MCWertGaming** [comment]
yeah but I have an idea to skip the rewrite. Also my change doesn't work that well as I have just changed the not working macro into an not working inline function. We need an different option here. Also the keys example is interpreting the ALT keys differently than the promt. That's why one has a critical problem and the other one does not. I would suggest to take a entirely different approach here. But we can merge my first try of course, I would change that later on then.

**Comment by certik** [comment]
I see. Yes, we can design a new approach.

**Comment by MCWertGaming** [comment]
Done! #113 provides a new approach.
