### ISSUE TITLE
improve standalone test

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#109]
As my project broke (again) because the master master branch of cpp-terminal has functions which are not declared as static and included into two source files that get compiled together, I would like to add another source file to the stand-alone test to avoid such mistakes in the future.

**Comment by certik** [comment]
We should also probably move all functions into `cpp` and use the header file for declarations only. That should take care of this problem.

**Comment by MCWertGaming** [comment]
Yeah exactly. I would like to do that and then add the optional compile options I have already collected and combine them with turning all warnings into errors (which will require some extra work as the integration tests throw some warnings already).

**Comment by certik** [comment]
Sure. I reviewed all of them now. Let me know if anything is not reviewed.

**Comment by MCWertGaming** [comment]
Fixed in #132. Closing this...
