### ISSUE TITLE
Fix loading the old terminal state on windows

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#135]
When running the menu example the terminal is set back into it's old state, but the command prompt is in the first line of the terminal again, which draws ontop of the old cmmands. See #132 for reference.

**Comment by flagarde** [comment]
@MCWertGaming This is solved I think with the last PR

**Comment by flagarde** [comment]
@MCWertGaming @certik It seems this has been solved
