### ISSUE TITLE
add static analysis like clang-tidy / cpptest / other solutions (if possible)

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#149]
We should enforce clang-tidy and cppcheck tests for this project (like we do with clang-format) to keep our code nicely clean and optimized.

**Comment by flagarde** [comment]
Please have a look to https://pre-commit.com/ it have nice features and can be directly added to github https://pre-commit.ci/

For clang-format for example it can make the changes and pull the change back to the PR.

**Comment by MCWertGaming** [comment]
I have pre-commit already in my projects that use golang as it's provided in the official github linting action. We should check out if it's supporting clang-format as well and if so simply replace the clang-format-action we are currently using.

**Comment by flagarde** [comment]
It's possible I use it in other project and cpplint too it think

**Comment by MCWertGaming** [comment]
Moved into #182.

**Comment by flagarde** [comment]
Do you have the admin right to activate pre-commit on the repo? 

I can make a PR for some of the points

**Comment by MCWertGaming** [comment]
I don't have org access sadly, but since it's not an application I can add it.
