### ISSUE TITLE
change default arguments like `unicode` to be automatically

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#153]
Currently, unicode has to be set manually - eiter on or off. I think that we should try to detect unicode support on runtime instead.

**Comment by MCWertGaming** [comment]
For linux:
https://www.rosettacode.org/wiki/Terminal_control/Unicode_output#C

**Comment by flagarde** [comment]
@MCWertGaming this check locale support utf8 but terminal be configure to use other encding. I provide a very basic utf8 terminal support detection in #294, seems to work so far. I adapt the code to use it on windons*.cpp but it need more cleaning in other PR
