### ISSUE TITLE
Is there a minimum version of GNU this should build with on Linux?

### ISSUE THREAD

**Issue by CharlesBunders** [jupyter-xeus/cpp-terminal#201]
Error I am getting after issuing cmake.

cbunders@Debian-Desktop:~/dev/cpp-terminal2/bld$ cmake ..
-- The CXX compiler identification is GNU 6.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cbunders/dev/cpp-terminal2/bld
cbunders@Debian-Desktop:~/dev/cpp-terminal2/bld$ ls
CMakeCache.txt       Makefile  cmake_install.cmake              examples
CMakeFiles           _deps     cpp-terminal                     tests
CTestTestfile.cmake  cmake     cpp-terminalConfigVersion.cmake
cbunders@Debian-Desktop:~/dev/cpp-terminal2/bld$ make
[  3%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/base.cpp.o
In file included from /usr/include/c++/6/memory:81:0,
                 from /home/cbunders/dev/cpp-terminal2/cpp-terminal/private/platform.hpp:25,
                 from /home/cbunders/dev/cpp-terminal2/cpp-terminal/base.hpp:4,
                 from /home/cbunders/dev/cpp-terminal2/cpp-terminal/base.cpp:1:
/usr/include/c++/6/bits/unique_ptr.h: In instantiation of 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = termios]':
/usr/include/c++/6/bits/unique_ptr.h:239:17:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = termios; _Dp = std::default_delete<termios>]'
/usr/include/c++/6/bits/unique_ptr.h:204:61:   required from 'constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr(std::nullptr_t) [with _Tp = termios; _Dp = std::default_delete<termios>; std::nullptr_t = std::nullptr_t]'
/home/cbunders/dev/cpp-terminal2/cpp-terminal/private/platform.hpp:65:50:   required from here
/usr/include/c++/6/bits/unique_ptr.h:74:22: error: invalid application of 'sizeof' to incomplete type 'termios'
  static_assert(sizeof(_Tp)>0,
                      ^
cpp-terminal/CMakeFiles/cpp-terminal.dir/build.make:75: recipe for target 'cpp-terminal/CMakeFiles/cpp-terminal.dir/base.cpp.o' failed
make[2]: *** [cpp-terminal/CMakeFiles/cpp-terminal.dir/base.cpp.o] Error 1
CMakeFiles/Makefile2:170: recipe for target 'cpp-terminal/CMakeFiles/cpp-terminal.dir/all' failed
make[1]: *** [cpp-terminal/CMakeFiles/cpp-terminal.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CharlesBunders** [comment]
I should add this is on ARM Linux.

**Comment by flagarde** [comment]
Hi, For now it need GNU 9 I think but I'm working on lowering this number :)

**Comment by flagarde** [comment]
Could you try the fork here : https://github.com/flagarde/cpp-terminal . It should run on clang>=3.5 and gcc>4.7 

I test it with github-action so I would be very nice to have some feedback from you :)

**Comment by CharlesBunders** [comment]
That fork builds okay for me. Thanks!

In the menu example I am getting some strange behavior. Terminal is UTF-8 (Mate and XTerm). Neither seems to render the box around the menu correctly. I will play a bit with terminal settings and see what happens.

Build result:

cbunders@Debian-Desktop:~/dev/flagarde-cpp-term$ mkdir bld && cd bld
cbunders@Debian-Desktop:~/dev/flagarde-cpp-term/bld$ cmake ..
-- The CXX compiler identification is GNU 6.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cbunders/dev/flagarde-cpp-term/bld
cbunders@Debian-Desktop:~/dev/flagarde-cpp-term/bld$ make
[  3%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/base.cpp.o
[  6%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/prompt.cpp.o
[  9%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/window.cpp.o
[ 12%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/input.cpp.o
[ 16%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/private/platform.cpp.o
[ 19%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/key.cpp.o
[ 22%] Linking CXX static library libcpp-terminal.a
[ 22%] Built target cpp-terminal
[ 25%] Building CXX object tests/CMakeFiles/test_terminal.dir/test_terminal.cpp.o
In file included from /usr/include/c++/6/vector:63:0,
                 from /home/cbunders/dev/flagarde-cpp-term/bld/_deps/doctest-src/doctest/doctest.h:3125,
                 from /home/cbunders/dev/flagarde-cpp-term/tests/test_terminal.cpp:2:
/usr/include/c++/6/bits/stl_uninitialized.h: In function '_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*; _ForwardIterator = doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*; _Allocator = std::allocator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase>]':
/usr/include/c++/6/bits/stl_uninitialized.h:304:69: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
   _GLIBCXX_MAKE_MOVE_IF_NOEXCEPT_ITERATOR(__last), __result, __alloc);
                                                                     ^
/usr/include/c++/6/bits/stl_uninitialized.h: In function '_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = std::fpos<__mbstate_t>*; _ForwardIterator = std::fpos<__mbstate_t>*; _Allocator = std::allocator<std::fpos<__mbstate_t> >]':
/usr/include/c++/6/bits/stl_uninitialized.h:304:69: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
   _GLIBCXX_MAKE_MOVE_IF_NOEXCEPT_ITERATOR(__last), __result, __alloc);
                                                                     ^
/usr/include/c++/6/bits/stl_uninitialized.h: In function '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>; _ForwardIterator = doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*; _Tp = doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase]':
/usr/include/c++/6/bits/stl_uninitialized.h:279:5: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
     __uninitialized_copy_a(_InputIterator __first, _InputIterator __last,
     ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_uninitialized.h:279:5: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
/usr/include/c++/6/bits/stl_uninitialized.h:281:63: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
     { return std::uninitialized_copy(__first, __last, __result); }
                                                               ^
/usr/include/c++/6/bits/stl_uninitialized.h: In function '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<std::fpos<__mbstate_t>*>; _ForwardIterator = std::fpos<__mbstate_t>*; _Tp = std::fpos<__mbstate_t>]':
/usr/include/c++/6/bits/stl_uninitialized.h:279:5: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
     __uninitialized_copy_a(_InputIterator __first, _InputIterator __last,
     ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_uninitialized.h:279:5: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
/usr/include/c++/6/bits/stl_uninitialized.h:281:63: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
     { return std::uninitialized_copy(__first, __last, __result); }
                                                               ^
/usr/include/c++/6/bits/stl_uninitialized.h: In function '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>; _ForwardIterator = doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*]':
/usr/include/c++/6/bits/stl_uninitialized.h:107:5: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
     uninitialized_copy(_InputIterator __first, _InputIterator __last,
     ^~~~~~~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_uninitialized.h:107:5: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
/usr/include/c++/6/bits/stl_uninitialized.h:126:41: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
  __uninit_copy(__first, __last, __result);
                                         ^
/usr/include/c++/6/bits/stl_uninitialized.h: In function '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<std::fpos<__mbstate_t>*>; _ForwardIterator = std::fpos<__mbstate_t>*]':
/usr/include/c++/6/bits/stl_uninitialized.h:107:5: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
     uninitialized_copy(_InputIterator __first, _InputIterator __last,
     ^~~~~~~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_uninitialized.h:107:5: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
/usr/include/c++/6/bits/stl_uninitialized.h:126:41: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
  __uninit_copy(__first, __last, __result);
                                         ^
/usr/include/c++/6/bits/stl_uninitialized.h: In static member function 'static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>; _ForwardIterator = doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*; bool _TrivialValueTypes = false]':
/usr/include/c++/6/bits/stl_uninitialized.h:68:9: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
         __uninit_copy(_InputIterator __first, _InputIterator __last,
         ^~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_uninitialized.h:68:9: note: parameter passing for argument of type 'std::move_iterator<doctest::{anonymous}::JUnitReporter::JUnitTestCaseData::JUnitTestCase*>' will change in GCC 7.1
/usr/include/c++/6/bits/stl_uninitialized.h: In static member function 'static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<std::fpos<__mbstate_t>*>; _ForwardIterator = std::fpos<__mbstate_t>*; bool _TrivialValueTypes = false]':
/usr/include/c++/6/bits/stl_uninitialized.h:68:9: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
/usr/include/c++/6/bits/stl_uninitialized.h:68:9: note: parameter passing for argument of type 'std::move_iterator<std::fpos<__mbstate_t>*>' will change in GCC 7.1
[ 29%] Linking CXX executable test_terminal
[ 29%] Built target test_terminal
[ 32%] Building CXX object examples/CMakeFiles/prompt_multiline.dir/prompt_multiline.cpp.o
[ 35%] Linking CXX executable prompt_multiline
[ 35%] Built target prompt_multiline
[ 38%] Building CXX object examples/CMakeFiles/prompt_immediate.dir/prompt_immediate.cpp.o
[ 41%] Linking CXX executable prompt_immediate
[ 41%] Built target prompt_immediate
[ 45%] Building CXX object examples/CMakeFiles/prompt_not_immediate.dir/prompt_not_immediate.cpp.o
[ 48%] Linking CXX executable prompt_not_immediate
[ 48%] Built target prompt_not_immediate
[ 51%] Building CXX object examples/CMakeFiles/prompt_simple.dir/prompt_simple.cpp.o
[ 54%] Linking CXX executable prompt_simple
[ 54%] Built target prompt_simple
[ 58%] Building CXX object examples/CMakeFiles/kilo.dir/kilo.cpp.o
[ 61%] Linking CXX executable kilo
[ 61%] Built target kilo
[ 64%] Building CXX object examples/CMakeFiles/menu.dir/menu.cpp.o
[ 67%] Linking CXX executable menu
[ 67%] Built target menu
[ 70%] Building CXX object examples/CMakeFiles/menu_window.dir/menu_window.cpp.o
[ 74%] Linking CXX executable menu_window
[ 74%] Built target menu_window
[ 77%] Building CXX object examples/CMakeFiles/menu_window_24bit.dir/menu_window_24bit.cpp.o
[ 80%] Linking CXX executable menu_window_24bit
[ 80%] Built target menu_window_24bit
[ 83%] Building CXX object examples/CMakeFiles/keys.dir/keys.cpp.o
[ 87%] Linking CXX executable keys
[ 87%] Built target keys
[ 90%] Building CXX object examples/CMakeFiles/colors.dir/colors.cpp.o
[ 93%] Linking CXX executable colors
[ 93%] Built target colors
[ 96%] Building CXX object examples/CMakeFiles/read_stdin.dir/read_stdin.cpp.o
[100%] Linking CXX executable read_stdin
[100%] Built target read_stdin

**Comment by flagarde** [comment]
Yes I had to make some change and maybe I introduced some bugs :(. At least I know it's compiling on arm. We are working on a better CI. We still need time to go down to gcc6.

**Comment by flagarde** [comment]
Could you try on other arch with the same compiler version on https://github.com/jupyter-xeus/cpp-terminal if you have the same bug with `In the menu example` to check if the bug was introduced by my changes. Thx

**Comment by certik** [comment]
@flagarde, thanks for fixing it in your fork. Can you please submit a PR here as well?

**Comment by flagarde** [comment]
Hi @certik I can make a PR of course but I fear I included somes bugs while converting so we are discusing to improve the CI first I'm ready to make a PR on that soon. It will allow to run an many compiler system arch etc and check the errors and slowly fix them... I have not made all the tests during the move from gcc9 to gcc4.6 so some bugs were included.

**Comment by flagarde** [comment]
There is a big move to do on the Base class so it should need a special PR and discussion maybe...

**Comment by certik** [comment]
@flagarde just package your changes in a well isolated PRs, like you did with the CI PR, and we can get them in one by one.

**Comment by flagarde** [comment]
Thx, some PR is ongoing to have c++17 gcc>4.7 on this repo... Maybe the fix is applied

**Comment by CharlesBunders** [comment]
Changing the font and restarting the terminals appears to have fixed the issue of it not rendering the box correctly. I will retest once these changes stabilize. For now, looks okay though.

**Comment by MCWertGaming** [comment]
Merged everything except the C++11 support, is the problem still occuring?

**Comment by CharlesBunders** [comment]
> Merged everything except the C++11 support, is the problem still occuring?

No. Build and run are good on ARM Linux.

**Comment by flagarde** [comment]
@MCWertGaming this can be closed?

**Comment by MCWertGaming** [comment]
Yeah, thank you really much everyone!
