### ISSUE TITLE
read_key0() exists in input.hpp but not in input.cpp

### ISSUE THREAD

**Issue by iganinja** [jupyter-xeus/cpp-terminal#236]
read_key0() exists in input.hpp but not in input.cpp, creating an undefined reference error when building.

**Comment by flagarde** [comment]
@iganinja I think it's because there is still missing the #234

**Comment by flagarde** [comment]
@iganinja  should be solved

**Comment by MCWertGaming** [comment]
Sorry about that, I'll look into merging PRs a bit faster ^^

**Comment by flagarde** [comment]
> Sorry about that, I'll look into merging PRs a bit faster ^^

No, it was my fault. Mea Culpa
