### ISSUE TITLE
Color are wrong with unicode characters on Windows

### ISSUE THREAD

**Issue by anupamsr** [jupyter-xeus/cpp-terminal#237]
Source code of colors.cpp
![image](https://user-images.githubusercontent.com/301019/230840363-40b274a0-b38a-40d0-98a4-16787cdd699f.png)
Output on windows 11 terminal
![image](https://user-images.githubusercontent.com/301019/230839866-56eaa887-b4e5-47c0-9d31-141e5bcd6914.png)
On linux (wsl)
![image](https://user-images.githubusercontent.com/301019/230840590-9b524f99-4b69-4f7e-ba41-bf52e34f23a9.png)

Am I missing some flag?

**Comment by flagarde** [comment]
@anupamsr Do you know which font is used in your terminal for the emoji ? I think it is a font problem. I would plan to use the same font for windows terminal and linux https://unifoundry.com/unifont/ I have made some try it's working on win10 and 11 but it's not implemented yet. Unicode(utf8) for windows is still buggy I guess.

**Comment by anupamsr** [comment]
You are right. I am using nerd font version of AnonymousPro. I changed the font and it is working correctly. Thanks.
