### ISSUE TITLE
exception leaking destructor is dangerous

### ISSUE THREAD

**Issue by flagarde** [jupyter-xeus/cpp-terminal#248]
Exception leaking from destructor (terminal class) is dangerous. In cpp-terminal case it could be avoid because : 
1) As is a cross-plaform library even if they was no problem the programer don't know which system the program will be run on so it should be needed to add many case base on plaftorm which would destroy our work on a cross-platform library

2) c++11 by default put noexcept on destructor so if destructor throw something the program call terminate and this avoid cleaning.

3) With the 2 stage nifty counter we could crash at the beginning if we can't open the file descriptors for the terminal. Then if it's open the function should never gives error because we talk directly to terminal (not cin cout etc)

**Comment by certik** [comment]
Can you show in the source code where an exception can happen in the destructor?

**Comment by flagarde** [comment]
On the terminal.cpp inside platform folder.. it was like this since the beginning I think but IMHO we should avoid that... The nifty counter should help

**Comment by certik** [comment]
I see, that has indeed been there from the beginning. However, the destructor was marked as `noexcept(false)` which might be ok. That was removed in https://github.com/jupyter-xeus/cpp-terminal/pull/215, so after that it's definitely a problem.

**Comment by flagarde** [comment]
@certik Yes is turned bad, (My idea was to delete it much before but I used it for test). However even with noexcept(false) is still no safe  if an exception as been raised and and other one appears on the destructor

**Comment by flagarde** [comment]
This could help #242 even if it's not the main purpose

**Comment by certik** [comment]
I think you can catch exceptions in destructors, you just can't leak them, correct?

So why don't we catch the exceptions that we throw. If they happen, then I can see two ways forward:

* We print to stdout that an exception occurred and do nothing otherwise
* We introduce an "error" global variable initialized to "false", and set it to "true" if an exception happened in the destructor. Then the caller can query this global variable, we can provide some function to hides this "internal API".

Is there any other option?

**Comment by flagarde** [comment]
@certik In c++11 It is not safe to don't catch on destructor you are right. 

Indeed is the option I have thought of. For the first one given we don't know the state (how bad the terminal is) it is maybe not the best option. Point two seems good for me. But I really think with #242 most of the problem will disappear and we can provide solution 2 for very careful programers.

**Comment by certik** [comment]
Ok, let's do #242 and option 2. That should be good enough.

**Comment by flagarde** [comment]
@certik @MCWertGaming As soon as the PR will be merge I will work on this. I need to check if it's possible because to my understanding the nifty counter would stay alive after the return in main().. Maybe there is some tricks but I would like to start with a clean/merged version
