### ISSUE TITLE
build as shared library, error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by topazus** [jupyter-xeus/cpp-terminal#249]
```bash
❯ cmake . -B build -DBUILD_SHARED_LIBS:BOOL=ON && cmake --build build -j6
-- The CXX compiler identification is GNU 13.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (15.6s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ruby/build/cpp-terminal/build
[  4%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/terminal.cpp.o
[  8%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/tty.cpp.o
[ 10%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/screen.cpp.o
[ 12%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/cursor.cpp.o
[  8%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/terminfo.cpp.o
[  8%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/input.cpp.o
[ 14%] Linking CXX shared library libcpp-terminal-platforms.so
[ 14%] Built target cpp-terminal-platforms
[ 20%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/input.cpp.o
[ 20%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/prompt.cpp.o
[ 22%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/window.cpp.o
[ 26%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/key.cpp.o
[ 22%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/terminal.cpp.o
[ 24%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/color.cpp.o
[ 28%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/event.cpp.o
[ 30%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/screen.cpp.o
[ 32%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/options.cpp.o
[ 34%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/cursor.cpp.o
[ 36%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/style.cpp.o
[ 38%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/io.cpp.o
[ 40%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/version.cpp.o
[ 42%] Linking CXX shared library libcpp-terminal.so
[ 42%] Built target cpp-terminal
[ 55%] Building CXX object tests/CMakeFiles/AttachConsole.dir/attach_console.test.cpp.o
[ 55%] Building CXX object examples/CMakeFiles/cin.dir/cin.cpp.o
[ 55%] Building CXX object examples/CMakeFiles/prompt_immediate.dir/prompt_immediate.cpp.o
[ 55%] Building CXX object examples/CMakeFiles/prompt_multiline.dir/prompt_multiline.cpp.o
[ 55%] Building CXX object tests/CMakeFiles/test_terminal.dir/test_terminal.cpp.o
[ 55%] Building CXX object examples/CMakeFiles/minimal.dir/minimal.cpp.o
[ 57%] Linking CXX executable minimal
[ 57%] Built target minimal
[ 59%] Linking CXX executable cin
[ 61%] Building CXX object examples/CMakeFiles/prompt_not_immediate.dir/prompt_not_immediate.cpp.o
[ 63%] Linking CXX executable AttachConsole
/usr/bin/ld: CMakeFiles/cin.dir/cin.cpp.o: undefined reference to symbol '_ZN4Term8Terminal17store_and_restoreEv'
/usr/bin/ld: /home/ruby/build/cpp-terminal/build/cpp-terminal/platforms/libcpp-terminal-platforms.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [examples/CMakeFiles/cin.dir/build.make:98: examples/cin] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:322: examples/CMakeFiles/cin.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/AttachConsole.dir/attach_console.test.cpp.o: undefined reference to symbol '_ZN4Term15is_stdout_a_ttyEv'
/usr/bin/ld: /home/ruby/build/cpp-terminal/build/cpp-terminal/platforms/libcpp-terminal-platforms.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [tests/CMakeFiles/AttachConsole.dir/build.make:98: tests/AttachConsole] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:270: tests/CMakeFiles/AttachConsole.dir/all] Error 2
[ 65%] Linking CXX executable prompt_immediate
[ 67%] Linking CXX executable prompt_multiline
[ 67%] Built target prompt_immediate
/usr/bin/ld: CMakeFiles/prompt_multiline.dir/prompt_multiline.cpp.o: undefined reference to symbol '_ZN4Term14is_stdin_a_ttyEv'
/usr/bin/ld: /home/ruby/build/cpp-terminal/build/cpp-terminal/platforms/libcpp-terminal-platforms.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [examples/CMakeFiles/prompt_multiline.dir/build.make:98: examples/prompt_multiline] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:374: examples/CMakeFiles/prompt_multiline.dir/all] Error 2
[ 69%] Linking CXX executable prompt_not_immediate
[ 69%] Built target prompt_not_immediate
[ 71%] Linking CXX executable test_terminal
[ 71%] Built target test_terminal
gmake: *** [Makefile:146: all] Error 2

ruby in 🌐 fedora in cpp-terminal on  master via △ v3.26.3 took 19s 
❯ nano cpp-terminal/CMakeLists.txt 

ruby in 🌐 fedora in cpp-terminal on  master [!] via △ v3.26.3 took 9s 
❯ git diff 
diff --git a/cpp-terminal/CMakeLists.txt b/cpp-terminal/CMakeLists.txt
index 8ab18bc..21e8c97 100644
--- a/cpp-terminal/CMakeLists.txt
+++ b/cpp-terminal/CMakeLists.txt
@@ -5,7 +5,7 @@ add_subdirectory(platforms)
 
 # create and configure library target
 add_library(cpp-terminal prompt.cpp window.cpp input.cpp terminal.cpp color.cpp key.cpp event.cpp screen.cpp options.cpp cursor.cpp style.cpp io.cpp "${CMAKE_CURRENT_BINARY_DIR}/version.cpp")
-target_link_libraries(cpp-terminal PRIVATE Warnings::Warnings cpp-terminal::cpp-terminal-platforms)
+target_link_libraries(cpp-terminal PUBLIC Warnings::Warnings cpp-terminal::cpp-terminal-platforms)
 target_compile_options(cpp-terminal PRIVATE $<$<CXX_COMPILER_ID:MSVC>:/utf-8>)
 target_include_directories(cpp-terminal PUBLIC $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}> $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}> $<INSTALL_INTERFACE:include>)
 

ruby in 🌐 fedora in cpp-terminal on  master [!] via △ v3.26.3 
❯ cmake . -B build -DBUILD_SHARED_LIBS:BOOL=ON && cmake --build build -j6
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ruby/build/cpp-terminal/build
[ 14%] Built target cpp-terminal-platforms
[ 42%] Built target cpp-terminal
[ 53%] Linking CXX executable cin
[ 53%] Linking CXX executable prompt_immediate
[ 53%] Linking CXX executable minimal
[ 53%] Linking CXX executable prompt_multiline
[ 53%] Building CXX object tests/CMakeFiles/AttachConsole.dir/attach_console.test.cpp.o
[ 55%] Building CXX object tests/CMakeFiles/test_terminal.dir/test_terminal.cpp.o
[ 57%] Built target minimal
[ 59%] Built target prompt_immediate
[ 61%] Built target cin
[ 63%] Built target prompt_multiline
[ 65%] Building CXX object examples/CMakeFiles/prompt_simple.dir/prompt_simple.cpp.o
[ 67%] Building CXX object examples/CMakeFiles/kilo.dir/kilo.cpp.o
[ 69%] Building CXX object examples/CMakeFiles/menu.dir/menu.cpp.o
[ 71%] Linking CXX executable prompt_not_immediate
[ 73%] Built target prompt_not_immediate
[ 75%] Building CXX object examples/CMakeFiles/menu_window.dir/menu_window.cpp.o
[ 77%] Linking CXX executable AttachConsole
[ 77%] Built target AttachConsole
[ 79%] Linking CXX executable menu
[ 81%] Building CXX object examples/CMakeFiles/keys.dir/keys.cpp.o
[ 83%] Linking CXX executable kilo
[ 85%] Linking CXX executable prompt_simple
[ 85%] Built target menu
[ 87%] Building CXX object examples/CMakeFiles/colors.dir/colors.cpp.o
[ 87%] Built target kilo
[ 87%] Built target prompt_simple
[ 89%] Building CXX object examples/CMakeFiles/read_stdin.dir/read_stdin.cpp.o
[ 91%] Linking CXX executable menu_window
[ 91%] Built target menu_window
/home/ruby/build/cpp-terminal/examples/keys.cpp: In function ‘int main()’:
/home/ruby/build/cpp-terminal/examples/keys.cpp:66:15: warning: case value ‘525’ not in enumerated type ‘Term::Key::Value’ [-Wswitch]
   66 |               case Term::Key::ALT + Term::Key::ENTER: s = "Alt+ENTER"; break;
      |               ^~~~
[ 93%] Linking CXX executable keys
[ 95%] Linking CXX executable colors
[ 95%] Built target keys
[ 97%] Linking CXX executable read_stdin
[ 97%] Built target colors
[ 97%] Built target read_stdin
[100%] Linking CXX executable test_terminal
[100%] Built target test_terminal

ruby in 🌐 fedora in cpp-terminal on  master [!] via △ v3.26.3 took 2s 
❯ ctest --test-dir build/
Internal ctest changing into directory: /home/ruby/build/cpp-terminal/build
Test project /home/ruby/build/cpp-terminal/build
    Start 1: UTF conversions
1/1 Test #1: UTF conversions ..................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.00 sec
```

It can be solved by change the `PRIVATE` specification of `target_link_libraries` of `cpp-terminal` to `PUBLIC`.

Quote: https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html
> Generally, a dependency should be specified in a use of [target_link_libraries()](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#command:target_link_libraries) with the PRIVATE keyword if it is used by only the implementation of a library, and not in the header files. If a dependency is additionally used in the header files of a library (e.g. for class inheritance), then it should be specified as a PUBLIC dependency.

https://github.com/jupyter-xeus/cpp-terminal/blob/f4989069f565b00aa60a50c51682dbbde336ae49/cpp-terminal/CMakeLists.txt#L6-L11

Ref: https://stackoverflow.com/questions/63524688/undefined-reference-to-symbol-symbol-error-adding-symbols-dso-missing-f

**Comment by flagarde** [comment]
It seems the problem is not an header problem but the linker problem... In the cin function that is inlined so the store_and_restore is not linked correctly.. what is strange is that kt is working on CI

**Comment by flagarde** [comment]
@topazus could you provide your CC CXX environment variables? Or tell my the fedora ones

**Comment by topazus** [comment]
The above build errors appeared when linking to libcpp-terminal-platforms.so.

**Comment by topazus** [comment]
> Other option would not be to make cpp-terminal-platforms STATIC ?

Marking cpp-terminal-platforms as STATIC can solve the problem.
```bash
❯ git diff
diff --git a/cpp-terminal/platforms/CMakeLists.txt b/cpp-terminal/platforms/CMakeLists.txt
index f886fee..f878d7c 100644
--- a/cpp-terminal/platforms/CMakeLists.txt
+++ b/cpp-terminal/platforms/CMakeLists.txt
@@ -1,4 +1,4 @@
-add_library(cpp-terminal-platforms terminal.cpp tty.cpp terminfo.cpp input.cpp screen.cpp cursor.cpp)
+add_library(cpp-terminal-platforms STATIC terminal.cpp tty.cpp terminfo.cpp input.cpp screen.cpp cursor.cpp)
 target_link_libraries(cpp-terminal-platforms PRIVATE Warnings::Warnings)
 target_compile_options(cpp-terminal-platforms PRIVATE $<$<CXX_COMPILER_ID:MSVC>:/utf-8 /wd4668 /wd4514>)
 target_include_directories(cpp-terminal-platforms PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}> $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}> $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}> $<INSTALL_INTERFACE:include>)

ruby in 🌐 fedora in cpp-terminal on  master [!] via △ v3.26.3 
❯ rm -rf build/ && cmake . -B build -DBUILD_SHARED_LIBS=ON -DCPPTERMINAL_ENABLE_TESTING=OFF && cmake --build build/ -j6
-- The CXX compiler identification is GNU 13.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ruby/build/cpp-terminal/build
[  6%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/terminal.cpp.o
[  6%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/tty.cpp.o
[ 11%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/input.cpp.o
[  8%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/screen.cpp.o
[  6%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/terminfo.cpp.o
[ 13%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/cursor.cpp.o
[ 15%] Linking CXX static library libcpp-terminal-platforms.a
[ 15%] Built target cpp-terminal-platforms
[ 20%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/window.cpp.o
[ 22%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/prompt.cpp.o
[ 22%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/input.cpp.o
[ 24%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/color.cpp.o
[ 28%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/terminal.cpp.o
[ 28%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/key.cpp.o
[ 31%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/event.cpp.o
[ 35%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/cursor.cpp.o
[ 35%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/options.cpp.o
[ 37%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/style.cpp.o
[ 40%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/screen.cpp.o
[ 42%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/io.cpp.o
[ 44%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/version.cpp.o
[ 46%] Linking CXX shared library libcpp-terminal.so
[ 46%] Built target cpp-terminal
[ 57%] Building CXX object examples/CMakeFiles/cin.dir/cin.cpp.o
[ 57%] Building CXX object examples/CMakeFiles/prompt_immediate.dir/prompt_immediate.cpp.o
[ 57%] Building CXX object examples/CMakeFiles/minimal.dir/minimal.cpp.o
[ 60%] Building CXX object examples/CMakeFiles/prompt_simple.dir/prompt_simple.cpp.o
[ 60%] Building CXX object examples/CMakeFiles/prompt_multiline.dir/prompt_multiline.cpp.o
[ 60%] Building CXX object examples/CMakeFiles/prompt_not_immediate.dir/prompt_not_immediate.cpp.o
[ 66%] Linking CXX executable prompt_not_immediate
[ 73%] Linking CXX executable cin
[ 68%] Linking CXX executable prompt_simple
[ 68%] Linking CXX executable minimal
[ 71%] Linking CXX executable prompt_immediate
[ 71%] Linking CXX executable prompt_multiline
[ 73%] Built target cin
[ 73%] Built target minimal
[ 73%] Built target prompt_multiline
[ 73%] Built target prompt_immediate
[ 73%] Built target prompt_simple
[ 73%] Built target prompt_not_immediate
[ 80%] Building CXX object examples/CMakeFiles/kilo.dir/kilo.cpp.o
[ 80%] Building CXX object examples/CMakeFiles/menu.dir/menu.cpp.o
[ 80%] Building CXX object examples/CMakeFiles/menu_window.dir/menu_window.cpp.o
[ 82%] Building CXX object examples/CMakeFiles/keys.dir/keys.cpp.o
[ 84%] Building CXX object examples/CMakeFiles/read_stdin.dir/read_stdin.cpp.o
[ 86%] Building CXX object examples/CMakeFiles/colors.dir/colors.cpp.o
/home/ruby/build/cpp-terminal/examples/keys.cpp: In function ‘int main()’:
/home/ruby/build/cpp-terminal/examples/keys.cpp:66:15: warning: case value ‘525’ not in enumerated type ‘Term::Key::Value’ [-Wswitch]
   66 |               case Term::Key::ALT + Term::Key::ENTER: s = "Alt+ENTER"; break;
      |               ^~~~
[ 93%] Linking CXX executable menu_window
[ 93%] Linking CXX executable kilo
[ 93%] Linking CXX executable menu
[ 95%] Linking CXX executable keys
[ 97%] Linking CXX executable read_stdin
[100%] Linking CXX executable colors
[100%] Built target menu
[100%] Built target kilo
[100%] Built target read_stdin
[100%] Built target keys
[100%] Built target menu_window
[100%] Built target colors
```

btw, I have a suggestion about the doctest library of the tests, maybe we can first use `find_package(doctest)` first, if not found, then use FetchContent to get it.

https://github.com/jupyter-xeus/cpp-terminal/blob/f4989069f565b00aa60a50c51682dbbde336ae49/tests/CMakeLists.txt#L5-L23

**Comment by flagarde** [comment]
> The above build errors appeared when linking to libcpp-terminal-platforms.so, but the cpp-terminal links PRIVATE to cpp-terminal-platforms, which compiled target cpp-terminal-platforms is only visible to cpp-terminal, not available to the target that links cpp-terminal.

This is indeed what I want to have.. I guess your linux add some other options to gcc by default because on the CI Ubuntu there is no compilation errors.

**Comment by flagarde** [comment]
> > Other option would not be to make cpp-terminal-platforms STATIC ?
> 
> Marking cpp-terminal-platforms as STATIC can solve the problem.
> ```bash
> ❯ git diff
> diff --git a/cpp-terminal/platforms/CMakeLists.txt b/cpp-terminal/platforms/CMakeLists.txt
> index f886fee..f878d7c 100644
> --- a/cpp-terminal/platforms/CMakeLists.txt
> +++ b/cpp-terminal/platforms/CMakeLists.txt
> @@ -1,4 +1,4 @@
> -add_library(cpp-terminal-platforms terminal.cpp tty.cpp terminfo.cpp input.cpp screen.cpp cursor.cpp)
> +add_library(cpp-terminal-platforms STATIC terminal.cpp tty.cpp terminfo.cpp input.cpp screen.cpp cursor.cpp)
>  target_link_libraries(cpp-terminal-platforms PRIVATE Warnings::Warnings)
>  target_compile_options(cpp-terminal-platforms PRIVATE $<$<CXX_COMPILER_ID:MSVC>:/utf-8 /wd4668 /wd4514>)
>  target_include_directories(cpp-terminal-platforms PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}> $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}> $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}> $<INSTALL_INTERFACE:include>)
> 
> ruby in 🌐 fedora in cpp-terminal on  master [!] via △ v3.26.3 
> ❯ rm -rf build/ && cmake . -B build -DBUILD_SHARED_LIBS=ON  && cmake --build build/ -j6
> -- The CXX compiler identification is GNU 13.0.1
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done (0.2s)
> -- Generating done (0.0s)
> -- Build files have been written to: /home/ruby/build/cpp-terminal/build
> [  6%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/terminal.cpp.o
> [  6%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/tty.cpp.o
> [  6%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/terminfo.cpp.o
> [  8%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/screen.cpp.o
> [ 10%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/input.cpp.o
> [ 12%] Building CXX object cpp-terminal/platforms/CMakeFiles/cpp-terminal-platforms.dir/cursor.cpp.o
> [ 14%] Linking CXX static library libcpp-terminal-platforms.a
> [ 14%] Built target cpp-terminal-platforms
> [ 20%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/prompt.cpp.o
> [ 20%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/input.cpp.o
> [ 24%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/color.cpp.o
> [ 26%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/key.cpp.o
> [ 20%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/window.cpp.o
> [ 22%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/terminal.cpp.o
> [ 30%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/event.cpp.o
> [ 30%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/screen.cpp.o
> [ 32%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/options.cpp.o
> [ 34%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/cursor.cpp.o
> [ 38%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/io.cpp.o
> [ 38%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/style.cpp.o
> [ 40%] Building CXX object cpp-terminal/CMakeFiles/cpp-terminal.dir/version.cpp.o
> [ 42%] Linking CXX shared library libcpp-terminal.so
> [ 42%] Built target cpp-terminal
> [ 55%] Building CXX object examples/CMakeFiles/cin.dir/cin.cpp.o
> [ 55%] Building CXX object examples/CMakeFiles/prompt_multiline.dir/prompt_multiline.cpp.o
> [ 55%] Building CXX object tests/CMakeFiles/test_terminal.dir/test_terminal.cpp.o
> [ 55%] Building CXX object examples/CMakeFiles/minimal.dir/minimal.cpp.o
> [ 55%] Building CXX object examples/CMakeFiles/prompt_immediate.dir/prompt_immediate.cpp.o
> [ 55%] Building CXX object tests/CMakeFiles/AttachConsole.dir/attach_console.test.cpp.o
> [ 63%] Linking CXX executable AttachConsole
> [ 63%] Linking CXX executable prompt_multiline
> [ 63%] Linking CXX executable minimal
> [ 63%] Linking CXX executable cin
> [ 65%] Linking CXX executable prompt_immediate
> [ 67%] Linking CXX executable test_terminal
> [ 67%] Built target AttachConsole
> [ 67%] Built target minimal
> [ 67%] Built target prompt_immediate
> [ 67%] Built target cin
> [ 67%] Built target prompt_multiline
> [ 71%] Building CXX object examples/CMakeFiles/prompt_simple.dir/prompt_simple.cpp.o
> [ 73%] Building CXX object examples/CMakeFiles/kilo.dir/kilo.cpp.o
> [ 73%] Building CXX object examples/CMakeFiles/prompt_not_immediate.dir/prompt_not_immediate.cpp.o
> [ 75%] Building CXX object examples/CMakeFiles/menu_window.dir/menu_window.cpp.o
> [ 77%] Building CXX object examples/CMakeFiles/menu.dir/menu.cpp.o
> [ 85%] Linking CXX executable prompt_not_immediate
> [ 85%] Linking CXX executable prompt_simple
> [ 85%] Linking CXX executable kilo
> [ 85%] Linking CXX executable menu
> [ 85%] Built target test_terminal
> [ 87%] Linking CXX executable menu_window
> [ 89%] Building CXX object examples/CMakeFiles/keys.dir/keys.cpp.o
> /home/ruby/build/cpp-terminal/examples/keys.cpp: In function ‘int main()’:
> /home/ruby/build/cpp-terminal/examples/keys.cpp:66:15: warning: case value ‘525’ not in enumerated type ‘Term::Key::Value’ [-Wswitch]
>    66 |               case Term::Key::ALT + Term::Key::ENTER: s = "Alt+ENTER"; break;
>       |               ^~~~
> [ 91%] Linking CXX executable keys
> [ 91%] Built target prompt_simple
> [ 91%] Built target prompt_not_immediate
> [ 91%] Built target menu
> [ 91%] Built target menu_window
> [ 91%] Built target kilo
> [ 95%] Building CXX object examples/CMakeFiles/colors.dir/colors.cpp.o
> [ 95%] Building CXX object examples/CMakeFiles/read_stdin.dir/read_stdin.cpp.o
> [100%] Linking CXX executable read_stdin
> [100%] Linking CXX executable colors
> [100%] Built target keys
> [100%] Built target colors
> [100%] Built target read_stdin
> ```
> 
> btw, I have a suggestion about the doctest library of the tests, maybe we can first use `find_package(doctest)` first, if not found, then use FetchContent to get it. I also do not konw the logic here, if cmake > 3.11, fetch doctest, else use find_package to find doctest?
> 
> https://github.com/jupyter-xeus/cpp-terminal/blob/f4989069f565b00aa60a50c51682dbbde336ae49/tests/CMakeLists.txt#L5-L23

I don't want yo rely on system install... So i fetch it with the version I want... Cmake before 3.11 have no fetcontent so i try to find the package (even if i don't like this)

**Comment by flagarde** [comment]
@topazus STATIC is done in other PR that is waiting to be merged

**Comment by flagarde** [comment]
@topazus this is fixed now?

**Comment by topazus** [comment]
Thanks.
