### ISSUE TITLE
Create a list of projects that are using this library

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#257]
Hey, after the discussion in #252, I think that it would be really nice to create a list of external projects that are using this library.

**Comment by TobiasWallner** [comment]
you can add my editor: [Lime](https://github.com/TobiasWallner/Lime)

**Comment by certik** [comment]
@TobiasWallner awesome! I wanted to write a Vim like editor using cpp-terminal, that only implements the small subset of Vim that I personally use.

**Comment by flagarde** [comment]
@TobiasWallner Nice, can had your work of course. It's nice to see so project relying on it. Would a great help to see where all things should be polished. 

I would like to include mouse position report, focus/unfocus report. On windows it's easy, on linux some vt100 keys should activate it on terminal that support it and some parsing to the answer.

Have you found something missing you would like to be implemented?
