### ISSUE TITLE
Clarify what goes and what does not go into terminal.h

### ISSUE THREAD

**Issue by certik** [jupyter-xeus/cpp-terminal#26]
A good rule seems to be:

* color output
* keyboard input
* querying terminal properties such as whether we are running in a terminal, terminal dimensions, etc.
* Screen class, that works like ncurses window
* Unicode support (input, output, Screen)
* Multiplatform support

Improvements, redesigns, etc. would go into `terminal.h`. It seems it's possible to keep it under, say, 2000 lines of code and have all this functionality in. So `terminal.h` would act as a multiplatform ncurses replacement.

Everything else (such as widgets) would go into other header files (or a separate library).

This scope of `terminal.h` should be documented in the README.

**Comment by MCWertGaming** [comment]
@certik can we close this issue?

**Comment by certik** [comment]
Let's close this issue once it is documented in the README what the (new) structure is, what goes where and why.

**Comment by MCWertGaming** [comment]
Sure! I'll add it to #147.
