### ISSUE TITLE
Bring back the list of other similar libraries

### ISSUE THREAD

**Issue by certik** [jupyter-xeus/cpp-terminal#272]
Either into the README, or elsewhere in documentation.

This was removed in https://github.com/jupyter-xeus/cpp-terminal/pull/147, but I think we should put it back in. Here is how the list looked like before it was removed:

https://github.com/MCWertGaming/cpp-terminal/blob/5eb95484efbe3eeb147bb960c73420cfc521090e/README.md

**Comment by flagarde** [comment]
I can add it back of course and add #257

**Comment by certik** [comment]
I like the other languages for inspiration, they often have very good ideas how things can look like.

**Comment by flagarde** [comment]
ok let me add them ttoo. You are right they are sources of inspiration

**Comment by flagarde** [comment]
@certik Basic is done, we can polish later :)
