### ISSUE TITLE
Pressing Ctrl, Alt, Shift creates a copy paste event on windows?

### ISSUE THREAD

**Issue by TobiasWallner** [jupyter-xeus/cpp-terminal#279]
### Discussed in https://github.com/jupyter-xeus/cpp-terminal/discussions/278

<div type='discussions-op-text'>

<sup>Originally posted by **TobiasWallner** July 24, 2023</sup>
I was just trying to make my application so, that it would not trigger a re-render on held down control keys when I noticed that they do not create a key event that I could catch but a create an empty copy paste event. 
How am I supposted to distinguish them from other 'real' copy paste events?</div>

**Comment by flagarde** [comment]
@TobiasWallner I think this is fixed right ?

**Comment by TobiasWallner** [comment]
yes

**Comment by flagarde** [comment]
@TobiasWallner great, thx for the news. Closing it then
