### ISSUE TITLE
Exception thrown at this line when typeing to fast

### ISSUE THREAD

**Issue by TobiasWallner** [jupyter-xeus/cpp-terminal#301]
https://github.com/jupyter-xeus/cpp-terminal/blob/52699fd3d2d0342ffa7b358e3f8ebd69dd9042f4/cpp-terminal/event.cpp#L417C60-L417C60

That line throws the following exception when I am typeing too fast or useing multibyte utf8 characters_
```Bash
Unhandled exception at 0x00007FFFAE3A024E (ucrtbased.dll) in lime.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

Why are we using a std::unique pointer and allocate a new string on every unicode character that is longer than one byte here? At least I will enter this code block whenever I hit one. Seems a little inefficient to me. Why did we move away from the std::string that just keeps its last allocated storage? 

it seems like at some point in the `std::unique_ptr::reset()` function the following code will be invoked:

```C++
_CRT_SECURITYCRITICAL_ATTRIBUTE
void __CRTDECL operator delete(void* const block) noexcept
{
    #ifdef _DEBUG
    _free_dbg(block, _UNKNOWN_BLOCK);
    #else
    free(block);
    #endif
}

```

and `_free_dbg(block, _UNKNOWN_BLOCK);` will then throw and probably `free(block);` is throwing in Release builds because it happens in Debug and Release builds.
Happens on GCC, Clang and MSVC.
It is very hard for me to figure out more since I beliefe that this exception is comeing from a detatched thread that reads the input.

**Comment by TobiasWallner** [comment]
>Why can't we simply append to the string?

or assign

**Comment by flagarde** [comment]
@certik @TobiasWallner I fully agree with all your comment. Sorry for this stupid change, will move back to string

**Comment by certik** [comment]
@flagarde awesome, thanks! No worries, this should be easy to fix.

**Comment by flagarde** [comment]
@certik @TobiasWallner Should be fixed now

**Comment by flagarde** [comment]
I tested quickly on linux but please have a try too because string inside union it's a bit tricky
