### ISSUE TITLE
Issue with file headers

### ISSUE THREAD

**Issue by Greeniac** [jupyter-xeus/cpp-terminal#352]
So if you include terminal.hpp in your cpp code with `#include "cpp-terminal/terminal.hpp"` it detects it fine, but inside terminal.hpp it tries to include terminal_impl.hpp with `#include "cpp-terminal/terminal_impl.hpp"` which is wrong, because its searching for cpp-terminal/terminal_impl.hpp relative to terminal.hpp's path, but since both files are in the same folder it cannot find it, so it should be `#include "terminal_impl.hpp"` instead, that goes the same for all header files.

**Comment by flagarde** [comment]
Hi, I'm not sure I understand your problem. Does this really triggers error at compile time ?

**Comment by Greeniac** [comment]
Yeah and here are a screenshot and the code:

```
#include "cpp-terminal/terminal.hpp"
#include <iostream>

int main()
{
  std::cout << "Just including terminal.hpp activate \033[31mcolor\033[0m !" << std::endl;
}
```
![errors](https://github.com/jupyter-xeus/cpp-terminal/assets/129557607/cd7306ae-f8db-4527-85c4-06b7aca05636)
