### ISSUE TITLE
use sourcefile instead of 'just' headers

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#67]
Hello,

i want to ask, if I can split the header files of this library into header and source files. Yes, I am aware of the desciption advertising this library as a "header only library", but I see many disadvantages here.

First of all we face many bad practices:
- function bodies inside classes
- internal enums and macros are exposed / included
- includes get included into all projects (that mean users can't keep on track, wich libraries are inlcuded with the two headers(with include themselves as well) so all includes are also available inside the main project)
- There are probably some more...

And I want to note, that this library is quiet small and consist of two headers. I would like to move the source parts into a source file and keep the class and function definitions inside of the header file (we can even move both header together, something you were / are already planing to do, if I saw that right). As most people (hopefully) use cpp-terminal as cmake dependency, there wouldn't be anything different for them at all, if they just copy the files they would have to copy two or 3/4 files and add the source file/s to their compile target - I wouldn't call that much more complicated.

Critizism is appreceated, it's an Idea - I hope this is not against the goal of this library!

Best regards
Damon

**Comment by certik** [comment]
Yeah, it's the usual issue of distributing C++ libraries. For [LFortran](https://gitlab.com/lfortran/lfortran/) I simply copy `cpp-terminal` into a [tpl](https://gitlab.com/lfortran/lfortran/-/blob/2f3950a3714fea34d56f04d42f99ec0c7363577d/src/bin/tpl/cpp-terminal/terminal.h) directory. So splitting into source/header files would not be a problem, I would just add the source file into LFortran's CMake file. So I am fine with that.

@wolfv, @SylvainCorlay what do you think is the best approach here?

**Comment by MCWertGaming** [comment]
I have looked into it and do you want to merge both terminal_base and terminal into one file? I think it would be better to do two seperate source files with seperate headers. I would even do a seperate header and source file to provide things like widgets and such. 
My Idea would be:
- terminal-base.hpp to provide the bare minimum to get you started with controling the terminal (that would include save_screen(), get_corsor_position(), the coloring and functions like that)
- terminal.hpp to provide a class with a developer friendly kind of abstraction that provides a small and simple set of functions which do most of the work in the background so the user don't needs to deal with that (like ncurses does).
- widgets.hpp / utils.hpp / extra.hpp (or however we will call it) for providing widgets to be used with terminal.hpp with things like progress bar, "windows" around text etc.
- optionally we can also provide a small header for optional things that are not associated with terminal but quiet usefull for writing application, I'm thinking about things like a sleep function and things like that

What do you think?

**Comment by MCWertGaming** [comment]
So what do you say?

**Comment by MCWertGaming** [comment]
Fixed in #132.
