### ISSUE TITLE
Create a wiki

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#70]
Until now, cpp-terminal is documented in examples and small snippets in the readme only. A wiki would give new users better a better understanding on what cpp-terminal is and how you can use it the best.

Help is really apreceated!

**Comment by MCWertGaming** [comment]
Also @certik I cannot edit the wiki right now, can add me?

**Comment by certik** [comment]
I already did, you have to accept the invite.

**Comment by MCWertGaming** [comment]
I saw it, thank you!

**Comment by certik** [comment]
@certik are you allowed to edit the wiki? If so, then this issue can be closed.

**Comment by MCWertGaming** [comment]
Yes, I have already added a page. I'll close this issue after #147 is merged.
