### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#74]
Adding versioning to cpp-terminal would allow developers depending on cpp-terminal to depend on a specific version of cpp-terminal and don't have to fear their applications to be broken by breaking changes for example.
This would include using the VERSION variable in cmake and providing a dedicated header cmake will generate and the creation of git tags (like on every pull-request merge).

**Comment by MCWertGaming** [comment]
Would it be better to provide the version inside something like cpp-terminal/info.h or rather a info.h inside of the root folder to store the project version number. CMake will create a simple macro you can use to something like print the version inside of your application, if you want to do that.

**Comment by certik** [comment]
You can create `cpp-terminal/version.h` and fill it with CMake.
