### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#75]
I was thinking about making the readme a bit prettier by adding CI checks, version (if added) and/or thing like code quality badges to the readme. Maybe some smaller visual changes too. I'll make a sample of what I think of soon.

**Comment by certik** [comment]
We can also record a video explaining the basics and show how to use it.

**Comment by MCWertGaming** [comment]
Sound awesome, maybe something like a small demo showing what's possible.
