### ISSUE TITLE
add dotfiles

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#76]
This is meant to add the usuall dotfiles. I'm thinking of a .gitingore and a .clang-format, but can be extended with .clang-tidy (static analysis), .gitpod (an online version of visual studio code, runs a free IDE on the web with everything included inside the file), GitHub codespaces (GitHub version of gitpod, runs visual studio code remote containers for free on the web). I don't know if all are actually usefull, but I wanted to note that they exist. There are even more, but I would prefer to keep it to the minimum required files.

**Comment by certik** [comment]
You can put in `.gitignore`.
