### ISSUE TITLE
tty status function location

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#86]
We already dicussed in #68 that we could move is_stdin_a_tty() and is_stdout_a_tty() outside of the class. As it is already a static member, no object is required. It's just a question of preference. What do you think? Rather leave everything as it is, or rather move both functions out of the class into the namespace?

**Comment by certik** [comment]
It doesn't matter to me that much.  We can move it out of the class if you want.

**Comment by MCWertGaming** [comment]
Fixed in #132.
