### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#90]
I have created the release tag `V1.0.0`. Do you agree on doing it like that? or would you prefer to do it different? And do you want to make a new release on every merged pull-request? Or rather like once a week or something like that?

**Comment by certik** [comment]
I removed that tag for now --- as you can see, we already have a v0.1.0 tag, so we should follow the same convention. Also I think we are not ready for 1.0.0 release yet. If you want to make a release, then we can do a v0.2.0 release.

**Comment by MCWertGaming** [comment]
Got it! Sorry.
