### ISSUE TITLE
Visual studio code terminal issue

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#95]
Hey,
i encountered some problems with cpp-terminal while working inside of visual studio code. The window class causes wrong colors on wrong parts on the screen and visual studio crashes sometimes while debugging. I will look into the cause (and will try to fix that) later on.

Here is what I mean:
![image](https://user-images.githubusercontent.com/39553804/109421451-43f12380-79cf-11eb-995a-69a10affa070.png)

The crash happens randomly, i'm not sure yet on how to replicate it.

**Comment by certik** [comment]
Thanks for noticing! I also use vscode. We need to fix that.

**Comment by MCWertGaming** [comment]
I have found an fix on this problem. Using "\n" while having an custom background color results in this effect. The foreground color has no issue with this at all. So we just need to make sure that Window and Window_24bit do "\033[0m" before "'\n". 4bit and 8bit colors have the same issue.

**Comment by MCWertGaming** [comment]
I have created an issue on their github:
https://github.com/microsoft/vscode/issues/120569
Also I have created a feature request on supporting more ANSI codes in the vscode integrated terminal
https://github.com/microsoft/vscode/issues/120569

**Comment by flagarde** [comment]
@MCWertGaming This is solved too https://github.com/jupyter-xeus/cpp-terminal/blob/d268df1039da9e38bf05efdc74480b3a91da9eb6/cpp-terminal/color.cpp#L84
