### ISSUE TITLE
merge window and window_24bit together

### ISSUE THREAD

**Issue by MCWertGaming** [jupyter-xeus/cpp-terminal#96]
We need to merge the `Term::Window` and `Term::WIndow_24bit` classes some day to avoid having the same code twice (and fix things twice too). The first idea of:
```
struct Color {
    enum { bit24, bit3, bit4 } tag;
    union {
        struct {
            char R, G, B;
        };   
        fg color_fg;
        fgB color_fgB;
    };  
};   
```
Didn't worked, because of the vectors and forbidden anonymous structures and unions. A different approach is required here.

**Comment by flagarde** [comment]
@MCWertGaming THis should be closed ?

**Comment by MCWertGaming** [comment]
Yeah, it's implemented, thanks for the work!
